feat: update aquaculture model
smart-data-models/dataModel.Aquaculture pull request #6
Opened 2022-09-19 13:56 UTC by AHABID

2022-09-19 17:37 UTC, albertoabellagarcia requested changes
please address the changes requested

2022-09-19 17:37 UTC, albertoabellagarcia commented on Specie/schema.json
> +{
There are no definitions.. ¿¿??

2022-09-19 17:37 UTC, albertoabellagarcia commented on Specie/examples/example-normalized.jsonld
> +{
It does not look like a real payload.

2022-09-19 17:37 UTC, albertoabellagarcia commented on Sump/schema.json
> +{
please the definitions could be more precise (indeed some of the could be available already in the search database https://smartdatamodels.org/index.php/ddbb-of-properties-descriptions/
Review them

2023-02-10 16:12 UTC, AHABID commented on Specie/examples/example-normalized.jsonld
> +{
fixed

2023-04-26 12:40 UTC, albertoabellagarcia commented
This modification is obsolete. Please reopen when there are actual contribution.

2023-04-26 12:40 UTC, closed without merging